version: 0.2

phases:
  install:
    commands:
    - pip install --upgrade awscli
    - npm install -g npm
    - npm install
  pre_build:
    commands:
    - npm test
  build:
    commands:
    - npm run build
    - sed -i -e "s|/PROD/|$WEBSITE_S3_PREFIX/public/|g" build/index.html
    - aws s3 cp --recursive build/ s3://$WEBSITE_S3_BUCKET/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
    - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
  - template-export.yml
