AWSTemplateFormatVersion: 2010-09-09
Description: The application stack.

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: Serverless React.js web application.

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        Content:
          Type: Api
          Properties:
            Path: /{any+}
            Method: get
        Index:
          Type: Api
          Properties:
            Path: /
            Method: get
